name: Frontend - Build & Push (Next.js standalone)

on:
  workflow_dispatch:
    inputs:
      api_url:
        description: "Backend URL (ej: http://IP:3000)"
        required: false
        type: string
  push:
    branches: [ "main" ]
    paths:
      - "**/*.ts"
      - "**/*.tsx"
      - "package.json"
      - "package-lock.json"
      - "Dockerfile"
      - ".github/workflows/docker-frontend.yml"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Resolver API URL
        id: cfg
        run: |
          API="${{ inputs.api_url }}"
          if [ -z "$API" ]; then API="${{ vars.NEXT_PUBLIC_API_URL }}"; fi
          echo "API=$API"
          echo "API=$API" >> $GITHUB_OUTPUT

      - name: Fail if API empty
        run: |
          if [ -z "${{ steps.cfg.outputs.API }}" ]; then
            echo "ERROR: No API URL provided."
            exit 1
          fi

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            NEXT_PUBLIC_API_URL=${{ steps.cfg.outputs.API }}
          tags: |
            ${{ secrets.DOCKER_USER }}/office-supply-frontend:latest
            ${{ secrets.DOCKER_USER }}/office-supply-frontend:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USER }}/office-supply-frontend:latest
          cache-to: type=inline